embedding_model:
  provider: google
  model_name: models/text-embedding-004

retriever:
  top_k: 5
  search_type: mmr
  fetch_k: 20
  lambda_mult: 0.5

llm:
  groq:
    model_name: llama-3.3-70b-versatile
    temperature: 0
    max_output_tokens: 2048
